version: '3'
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  web:
    build: .
    command: python mgnn-v1.4.7.py
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - redis